# Generated by Django 4.2.1 on 2023-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dataOfCreation',
            new_name='data_of_creation',
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
